comment:
  layout: "header, diff, flags, components" # show component info in the PR comment
component_management:
  default_rules: # default rules that will be inherited by all components
    statuses:
      - type: project # in this case every component that doens't have a status defined will have a project type one
        target: auto
        branches:
          - "!main"
  individual_components:
    - component_id: nicknamer
      name: nicknamer
      paths:
        - nicknamer/**
    - component_id: grrs
      name: grrs
      paths:
        - grrs/**
    - component_id: task-cli
      name: task-cli
      paths:
        - task-cli/**
    - component_id: hot_dog
      name: hot_dog
      paths:
        - hot_dog/**
