[package]
name = "mindreadr_core"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.16"
serde = { version = "1.0", features = ["derive"], optional = true }

[features]
default = []
serde = ["dep:serde"]
