//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "games")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub state: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub players: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::rounds::Entity")]
    Rounds,
}

impl Related<super::rounds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Rounds.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
