//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub use super::game_players::Entity as GamePlayers;
pub use super::games::Entity as Games;
pub use super::round_guesses::Entity as RoundGuesses;
pub use super::rounds::Entity as Rounds;
