//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "game_state")]
pub enum GameState {
    #[sea_orm(string_value = "waiting_for_players")]
    WaitingForPlayers,
    #[sea_orm(string_value = "in_progress")]
    InProgress,
    #[sea_orm(string_value = "finished")]
    Finished,
}
