//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub use super::game_players::Entity as GamePlayersEntity;
pub use super::games::Entity as GamesEntity;
pub use super::players::Entity as PlayersEntity;
pub use super::rounds::Entity as RoundsEntity;
