[package]
name = "nicknamer"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.27"
log4rs = { version = "1.3.0", features = ["console_appender"] }
poise = "0.6.1"
tokio = { version = "1.44.2", features = ["full"] }
