#!/usr/bin/env bash
#MISE description="Runs the web app locally"
#MISE sources=["Cargo.toml", "src/**/*.rs", "assets/**/*", "input.css", "tailwind.config.js"]
set -euo pipefail

# Define a cleanup function
cleanup() {
  echo "🧹 Cleaning up Docker Compose services..."
  docker compose down --remove-orphans
}

# Set the trap to call cleanup on EXIT, ERR, and INT signals
trap cleanup EXIT ERR INT


echo "🔧 Setting up Docker Compose services..."
docker compose up -d


# Run your main task
echo "🚀 Running web app with dx serve"
dx serve --platform web
