name: Rust Tests
permissions:
  contents: read
  pull-requests: write
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  MISE_EXPERIMENTAL: true
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Log in to Docker Hub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: rustup target add wasm32-unknown-unknown
      - run: |
          sudo apt update && sudo apt install -y \
            libglib2.0-dev \
            pkg-config \
            libssl-dev \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            libxdo-dev \
            patchelf
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4
      - run: mise run ci
      - uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2
        with:
          files: codecov.json
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
