env_files = [
   { path = "./.env", profile = "development"},
]

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.run]
command = "cargo"
args = [
    "run",
    "--bin",
    "nicknamer_server",
]

[tasks.insta-test]
description = "Run Insta snapshot tests"
command = "cargo"
args = ["insta", "test"]

[tasks.test]
description = "Run all tests (unit, integration, snapshot)"
dependencies = ["insta-test"]
command = "cargo"
args = ["test"]
